name: Build VoIPMatrix iOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install

      - name: Build App
        run: |
          xcodebuild \
          -workspace Linphone.xcworkspace \
          -scheme Linphone \
          -sdk iphoneos \
          -configuration Release \
          build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build
