name: Build VoIPMatrix iOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild \
          -project LinphoneApp.xcodeproj \
          -scheme Linphone \
          -sdk iphoneos \
          -configuration Release \
          build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build
