name: iOS Build

on:
push:
branches: [ "master", "main" ]

jobs:
build:
runs-on: macos-latest

```
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Show Xcode version
    run: xcodebuild -version

  - name: Build iOS
    run: |
      xcodebuild \
      -project LinphoneApp.xcodeproj \
      -scheme Linphone \
      -configuration Release \
      -sdk iphoneos \
      -destination "generic/platform=iOS" \
      CODE_SIGNING_ALLOWED=NO \
      build
```
