name: iOS Build

on:
push:

jobs:
build:
runs-on: macos-latest

```
steps:
  - uses: actions/checkout@v4

  - run: xcodebuild -version

  - run: |
      xcodebuild -workspace LinphoneApp.xcworkspace -scheme Linphone -configuration Release -sdk iphoneos -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO build
```
